name: Test Windows Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, Windows, X64, taxfrontend]

    steps:
      - name: Test Runner
        shell: powershell
        run: |
          Write-Host "===================================="
          Write-Host "GitHub Actions Runner is working"
          Write-Host "===================================="
          Write-Host "Computer Name: $env:COMPUTERNAME"
          Write-Host "User: $env:USERNAME"
          Write-Host "Workspace: $env:GITHUB_WORKSPACE"

      - name: Check Node
        shell: powershell
        run: |
          Write-Host "Node version:"
          node -v

          Write-Host "NPM version:"
          npm -v

      - name: Check IIS
        shell: powershell
        run: |
          Write-Host "IIS status:"
          iisreset /status